server:
  port: 9990
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: purchase-user
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/school_purchase?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 20
    minIdle: 10
    maxActive: 100
  devtools:
    restart:
      enabled: false
  messages:
    basename: i18n/message
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.163.com
    username: wanthkuail@163.com
    password: DLNOINYGDOZKANSK
    port: 25
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: false
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
    timeout: 1000
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
#  web:
#    resources:
#      static-locations: /static/**
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 12345678
  main:
    allow-circular-references: true
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
##    com.fastcollect.controller: info
##    com.fastcollect.service: info
#    com.fastcollect.dao.mapper: debug
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
purchase-default-data:
  AVATAR_URL: https://s3.bmp.ovh/imgs/2022/04/17/9aef00554c9335e0.png
  USER_UPLOAD_BASE_PATH: D:/code/1_my_projects/1-school-purchase/file/user
  AVATAR_UPLOAD_PATH: D:/code/1_my_projects/1-school-purchase/file/avatar
  AVATAR_ACCESS_BASE_URL: /file/avatar
  CONTRACT_UPLOAD_BASE_PATH: D:/code/1_my_projects/1-school-purchase/file/contract
  ATTACHMENT_ACCESS_BASE_URL: /file/user
  CONTRACT_ACCESS_BASE_URL: /file/contract